---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base.fullname" . }}-config
  labels:
{{ include "base.labels" $ | indent 4 }}
data:
  EXTRA_DUMMY: VALUE
{{- with .Values.env.variables }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.extraEnv }}
  {{- toYaml . | nindent 2 }}
{{- end }}
